"""Pure transform: ``ComplianceReport`` → ``ReportDocument``.

The on-disk JSON shape stays the source of truth. This builder is
the single point where the new client-aligned shape is derived for
both the renderer and the on-screen rule-table component.

Same input → same output. No I/O, no LLM calls, no side effects.
The mitigation-LLM-synthesis path is invoked separately (US3 /
``POST /mitigation/synthesize``) before this builder runs.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

from app.compliance.models import (
    AgentReport,
    ComplianceFinding,
    ComplianceReport,
    RuleResult,
)
from app.compliance.report_renderer.mitigation import pick_mitigation
from app.compliance.report_renderer.page_formatter import format_pages
from app.compliance.report_renderer.status_bucket import (
    LABELS,
    PRIORITY,
    bucket_status,
)
from app.compliance.report_renderer.summary import (
    concat_finding_evidence,
    summarise_compliant,
)
from app.compliance.report_renderer.types import (
    ReportDocument,
    ReportFooter,
    ReportHeader,
    ReportRow,
    ReportStats,
)

# Display names match the existing frontend constants in
# ``frontend/src/types/compliance.ts``.
AGENT_DISPLAY_NAMES: dict[str, str] = {
    "alcoa": "ALCOA+",
    "gmp": "GMP",
    "checklist": "Checklist",
    "sop": "SOP",
    "reconciliation": "Cross-Page",
}


# Disclaimer template — pre-filled by the builder. Two-brand-layer
# pattern: masthead (product name) shown in the header band;
# engine name ("BMR Compliance Intelligence") appears in the disclaimer. Matches
# the reference PDF's footer line-for-line.
_DISCLAIMER_TEMPLATE: str = (
    "Disclaimer Note : This document is electronically generated by "
    "BMR Compliance Intelligence Printed By: {operator} Printed On: {timestamp}"
)


def build_report_document(
    report: ComplianceReport,
    *,
    operator: str = "System",
    product_name: str = "BMR Compliance Intelligence Suite",
    logo_path: Path | None = None,
    agent_filter: str | None = None,
    now: datetime | None = None,
    metadata_overrides: dict[str, str] | None = None,
) -> ReportDocument:
    """Derive the client-aligned ``ReportDocument`` from the raw
    ``ComplianceReport`` JSON shape.

    * ``operator`` — surfaced in the footer disclaimer; defaults to
      "System" when no actor is bound to the request.
    * ``product_name`` — masthead brand. Override via
      ``AT_COMPLIANCE__REPORT_PRODUCT_NAME`` env var threaded by the
      route handler.
    * ``logo_path`` — generic compliance-suite logo. ``None`` falls
      back to text-only header.
    * ``agent_filter`` — when non-None, only rows for that agent
      surface (e.g. an operator wants the GMP-only export).
    * ``now`` — clock injection point for tests; defaults to
      ``datetime.now(UTC)``.
    * ``metadata_overrides`` — extra header rows from outside the
      ``ComplianceReport`` shape (typically Product / Batch No /
      BPCR Number, extracted from the OCR ``result.json`` by the
      route handler). Keys that already exist in the default
      metadata list (Document, Product, Batch No, Date Of
      Validation) replace the default value; new keys are appended.
    """

    now = now or datetime.now(UTC)

    # 1. Build rows from per-agent RuleResults.
    rows: list[ReportRow] = []
    excluded_not_applicable = 0
    for agent_report in report.agent_reports:
        if agent_filter and agent_report.agent != agent_filter:
            continue
        # Index findings per rule_id so we can pair RuleResult + findings.
        findings_by_rule: dict[str, list[ComplianceFinding]] = {}
        for f in agent_report.findings:
            findings_by_rule.setdefault(f.rule_id, []).append(f)

        for ev in agent_report.all_evaluations:
            row = _build_row(ev, agent_report, findings_by_rule.get(ev.rule_id, []))
            if row is None:
                excluded_not_applicable += 1
                continue
            rows.append(row)

    # 2. Sort: action_required first, then needs_attention, then
    # compliant. Within each bucket: by agent then rule_id for
    # deterministic order.
    rows.sort(key=lambda r: (PRIORITY[r.compliance_kind], r.agent, r.rule_id))

    # 3. Compute stats.
    stats = ReportStats(
        row_count=len(rows),
        compliant_count=sum(1 for r in rows if r.compliance_kind == "compliant"),
        action_required_count=sum(1 for r in rows if r.compliance_kind == "action_required"),
        needs_attention_count=sum(1 for r in rows if r.compliance_kind == "needs_attention"),
        excluded_not_applicable_count=excluded_not_applicable,
    )

    # 4. Header — derived from the report's document-level metadata.
    header = ReportHeader(
        product_name=product_name,
        title=_derive_title(report),
        is_draft=True,  # Stays True until HITL sign-off lands (future).
        metadata_rows=_build_metadata_rows(report, metadata_overrides),
        logo_path=logo_path,
    )

    # 5. Footer — disclaimer pre-filled with operator + timestamp.
    disclaimer = _DISCLAIMER_TEMPLATE.format(
        operator=operator,
        timestamp=now.strftime("%m/%d/%Y, %I:%M %p"),
    )
    footer = ReportFooter(
        operator_name=operator,
        generated_at=now,
        disclaimer=disclaimer,
    )

    return ReportDocument(
        header=header,
        rows=rows,
        footer=footer,
        stats=stats,
        priority_actions=list(report.executive_summary.priority_actions),
        key_risks=list(report.executive_summary.key_risks),
        strengths=list(report.executive_summary.strengths),
    )


def _build_row(
    ev: RuleResult,
    agent_report: AgentReport,
    findings: list[ComplianceFinding],
) -> ReportRow | None:
    """Build one row, or ``None`` if the rule should be excluded
    (status == not_applicable per FR-014).
    """

    # Pick up the HITL override from the worst-status finding (if any
    # exist). The HITL state is per-finding in the current data
    # model; for row-level rollup we take any "user_approved" as a
    # signal that the operator has cleared the rule.
    hitl_status: str | None = None
    for f in findings:
        if f.hitl_status == "user_approved":
            hitl_status = "user_approved"
            break
        if f.hitl_status == "user_rejected":
            hitl_status = "user_rejected"
            # Don't break — a later user_approved would win.

    kind = bucket_status(ev.status, hitl_status)
    if kind is None:
        return None

    # Compliant: pages cell is empty (FR-003); evidence is the
    # cross-page summary (FR-004); mitigation is "Not Applicable"
    # (FR-006a).
    if kind == "compliant":
        evidence_pages = ""
        detailed_evidence = summarise_compliant(ev)
        mitigation = "Not Applicable"
    else:
        finding_pages = sorted({pn for f in findings for pn in f.page_numbers})
        evidence_pages = format_pages(finding_pages) if finding_pages else format_pages(ev.page_numbers)
        # Prefer the RuleResult-level synthesized narrative when it exists —
        # it was produced by _synthesize_batch() and carries a cross-page
        # narrative with PAGE:N citations covering all relevant pages.
        # Per-finding concat is per-deduplication-winner text (one page only)
        # and is used only as a fallback when no synthesis happened.
        synth_text = (ev.reasoning or "").strip() or (ev.evidence or "").strip()
        per_finding_text = concat_finding_evidence(findings)
        if synth_text:
            detailed_evidence = synth_text
        elif per_finding_text:
            detailed_evidence = per_finding_text
        else:
            detailed_evidence = "The rule was flagged but no per-finding detail is recorded."
        mitigation = pick_mitigation(findings)

    return ReportRow(
        rule_id=ev.rule_id,
        agent=AGENT_DISPLAY_NAMES.get(ev.agent or agent_report.agent, ev.agent or agent_report.agent),
        question=ev.rule_text or ev.rule_id,
        compliance_label=LABELS[kind],
        compliance_kind=kind,
        evidence_pages=evidence_pages,
        detailed_evidence=detailed_evidence,
        mitigation=mitigation,
    )


def _derive_title(report: ComplianceReport) -> str:
    """Pick a report title from the document type. Matches the
    reference PDF's "Checklist based Review" exemplar."""

    dt = (report.document_type or "").lower()
    title_map = {
        "batch_record": "BMR Compliance Review",
        "ipc_report": "IPC Compliance Review",
        "analysis_report": "Analytical Compliance Review",
        "operation_checklist": "Operation Checklist Review",
        "raw_material_request": "Raw Material Compliance Review",
        "scada_report": "SCADA Data Review",
        "batch_closure": "Batch Closure Review",
        "qc_analytical_package": "QC Analytical Review",
        "certificate": "Certificate Review",
    }
    return title_map.get(dt, "Compliance Review")


def _build_metadata_rows(
    report: ComplianceReport,
    overrides: dict[str, str] | None = None,
) -> list[tuple[str, str]]:
    """Build the (label, value) pairs for the metadata block.

    The base rows come from ``ComplianceReport`` (filename + report
    generation date). Product / Batch / BPCR style fields live in
    the OCR ``result.json`` not the compliance report, so the route
    handler extracts them and threads them through ``overrides``.
    A matching key replaces the default placeholder; new keys are
    appended in the order they're given.
    """

    rows: list[tuple[str, str]] = [
        ("Document", report.filename or report.doc_id or "-"),
        ("Product", "-"),
        ("Batch No", "-"),
    ]

    # Date of validation = generation date (the report was created
    # when compliance ran). Format YYYY-MM-DD to match the reference.
    # ``generated_at`` is a ``datetime`` on the Pydantic model; some
    # legacy JSONs deserialise it as a string, hence the defensive
    # branch.
    gen = report.generated_at
    if isinstance(gen, datetime):
        rows.append(("Date Of Validation", gen.strftime("%Y-%m-%d")))
    elif isinstance(gen, str) and gen:
        try:
            gen_dt = datetime.fromisoformat(gen.replace("Z", "+00:00"))
            rows.append(("Date Of Validation", gen_dt.strftime("%Y-%m-%d")))
        except ValueError:
            rows.append(("Date Of Validation", "-"))
    else:
        rows.append(("Date Of Validation", "-"))

    if overrides:
        existing = {label: i for i, (label, _) in enumerate(rows)}
        for label, value in overrides.items():
            value = (value or "").strip()
            if not value:
                continue
            if label in existing:
                rows[existing[label]] = (label, value)
            else:
                rows.append((label, value))

    return rows
